Run_Search: 'True'
Run_WebApp: 'True'
ai_model: gpt-4o-mini
ai_rank: 'True'
config_directory: configs
config_modelname: QuantumOptics
default_theme: default_theme
host: OpenAI
lookback_date: '14'
output_db: articles.db
output_directory: ./articles
output_md: 'True'
output_pdf: ./articles/pdf
save_articles: 'True'
search_abstract: 'True'
search_title: 'True'
